name: Get Commit Message
on: [push]

jobs:
  print-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print commit message
        run: |
          MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit message: $MESSAGE"