name: Extract Feature

on:
  push:
    branches: [ "master" ]

jobs:
  get-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get PR description
        run: |
          PR_NUMBER=$(echo ${{ github.ref }} | awk 'BEGIN { FS = "/" } ; { print $3 }')
          PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X GET https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
            | jq -r ".body")
          echo "PR Description: $PR_DESCRIPTION"
          FEATURES=$(echo "$PR_DESCRIPTION" | sed -n 's/^.*feature: \(.*\)$/\1/p' | tr ',' '\n')
          for feature in $FEATURES; do
            echo "Feature: $feature"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}