name: Get confluence page by label

on:
  push:
    branches: [ master ]

jobs:
  get-confluence-page:
    runs-on: ubuntu-latest
    steps:
      - name: Get Page by Label
        id: confPage
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://risepeople.atlassian.net/wiki/rest/api/search?expand=metadata.labels&cql=label="hack-day-test"'
            method: 'GET'
            username: ${{ secrets.CONFLUENCE_SAM_USER }}
            password: ${{ secrets.CONFLUENCE_SAM_TOKEN }}
      - name: Extract pairs
        run: |
          CONFLUENCE_PAGE_IDS=$(echo -n '${{ steps.confPage.outputs.response }}' | jq -r '.results[].content.id')
          echo "PAGE_IDS: $CONFLUENCE_PAGE_IDS"
