name: Get confluence page by label

on:
  push:
    branches: [ master ]

jobs:
  get-confluence-page:
    runs-on: ubuntu-latest
    steps:
      - name: Get Page by Label
        id: confPage
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://risepeople.atlassian.net/wiki/rest/api/search?expand=metadata.labels&cql=label="hack-day-test"'
            method: 'GET'
            username: ${{ secrets.CONFLUENCE_SAM_USER }}
            password: ${{ secrets.CONFLUENCE_SAM_TOKEN }}
      - name: print res
        run: |
            CONFLUENCE_PAGES=$(echo '${{ steps.confPage.outputs.response }}' | jq -r -c '.results[].content.id')
            for conf in $CONFLUENCE_PAGES; do
             echo "PAGE: $conf"
             RES=$(curl -s -u ${{ secrets.CONFLUENCE_USER }}:${{ secrets.CONFLUENCE_TOKEN }} https://risepeople.atlassian.net/wiki/rest/api/content/$conf | jq -r '.space.id')
             echo "RESPONSE: $RES"
             
            #  echo '{"spaceId":$(echo $RES),"status":"current","title":"Commit messageasdfdfs ${RES} ${conf}","parentId":${conf},"body":{"representation":"storage","value":"hackday title unescaped"}}'
            #  CREATE_PAGE=$(curl -i --location 'https://risepeople.atlassian.net/wiki/api/v2/pages' \
            #   -u ${{ secrets.CONFLUENCE_USER }}:${{ secrets.CONFLUENCE_TOKEN }} \
            #   --header 'Content-Type: application/json' \
            #   --data '{"spaceId":$RES,"status":"current","title":"Commit messageasdfdfs $RES $conf","parentId":$conf,"body":{"representation":"storage","value":"hackday title unescaped"}}')
            #   echo "CREATE PAGE: $CREATE_PAGE"
            done
            # PAGESA=$(echo $CONFLUENCE_PAGES | tr ' ' ',')
            # echo "CONFPAG=$(echo $PAGESA)" >> $GITHUB_ENV

