name: Get confluence page by label

on:
  push:
    branches: [ master ]

jobs:
  get-confluence-page:
    runs-on: ubuntu-latest
    steps:
      - name: Get Page by Label
        id: confPage
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://risepeople.atlassian.net/wiki/rest/api/search?expand=metadata.labels&cql=label="hack-day-test"'
            method: 'GET'
            username: ${{ secrets.CONFLUENCE_SAM_USER }}
            password: ${{ secrets.CONFLUENCE_SAM_TOKEN }}
      - name: Extract pairs
        run: |
          PAIRS=$(echo -n '${{ steps.confPage.outputs.response }}' | jq -r '.results[] | "\(.content.id) \(.url | split("/") | .[2])"')
          echo "Pairs: $PAIRS"
          for pair in $PAIRS; do
            read id spaceID <<< $pair
            echo "ID: $id, SpaceID: $spaceID"
          done
