name: Extract Feature

on:
  push:
    branches: [ "master" ]

jobs:
  get-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get PR description
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit message: $COMMIT_MESSAGE"
          PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oP 'Merge pull request #\K\d+')
          echo "PR number: $PR_NUMBER"
          PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X GET https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
            | jq -r ".body")
          echo "PR Description: $PR_DESCRIPTION"
          FEATURES=$(echo "$PR_DESCRIPTION" | sed -n 's/^.*feature: \(.*\)$/\1/p' | tr ',' '\n')
          echo "Features: $FEATURES"

          for feature in $FEATURES; do
            echo "https://risepeople.atlassian.net/wiki/rest/api/search?cql=label=$feature"

            PAGES=$(curl --request GET \
              --url "https://risepeople.atlassian.net/wiki/rest/api/search?cql=label=$feature" \
              --user ${{ secrets.CONFLUENCE_SAM_USER }}:${{ secrets.CONFLUENCE_SAM_TOKEN }} \
              --header 'Accept: application/json')

            for page in $PAGES; do
              echo $page
            done
          done

          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}