name: Get confluence page by label

on:
  push:
    branches: [ master ]

jobs:
  get-confluence-page:
    runs-on: ubuntu-latest
    steps:
      - name: Get Page by Label
        id: confPage
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://risepeople.atlassian.net/wiki/rest/api/search?expand=metadata.labels&cql=label="hack-day-test"'
            method: 'GET'
            username: ${{ secrets.CONFLUENCE_SAM_USER }}
            password: ${{ secrets.CONFLUENCE_SAM_TOKEN }}
      - name: print res
        run: |
            page_ids=$(echo '${{ steps.confPage.outputs.response }}' | jq -r -c '.results[].content.id')
            for page_id in $page_ids; do
             echo "PAGE: $page_id"
             RES=$(curl -s -u ${{ secrets.CONFLUENCE_USER }}:${{ secrets.CONFLUENCE_TOKEN }} https://risepeople.atlassian.net/wiki/rest/api/content/$page_id | jq -r '.space.id')
             echo "RESPONSE: $RES"
            done

