name: Hack commit msg

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-commit-message:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Print commit message
        run: |
          echo Getting commit message...
          MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit message: $MESSAGE"
          echo Commit message printed!
