name: Extract Feature

on:
  push:
    branches: [ "master" ]

jobs:
  update-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create child page with PR information
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit message: $COMMIT_MESSAGE"
          PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oP 'Merge pull request #\K\d+')
          AUTHOR=$(echo "$COMMIT_MESSAGE" | grep -oP '(?<=from )[^/]+' )
          echo "PR number: $PR_NUMBER"

          PR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X GET https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER)
          PR_DESCRIPTION=$(echo $PR | jq -r ".body")
          PR_URL=$(echo $PR | jq -r ".html_url")
          FEATURES=$(echo "$PR_DESCRIPTION" | sed -n 's/^.*feature: \(.*\)$/\1/p' | tr ',' '\n')

          echo "PR Description: $PR_DESCRIPTION"
          echo "PR_URL: $PR_URL"

          for feature in $FEATURES; do
            PAGES=$(curl -s --request GET \
              --url "https://risepeople.atlassian.net/wiki/rest/api/search?expand=metadata.labels&cql=label=%22$feature%22" \
              --user ${{ secrets.CONFLUENCE_SAM_USER }}:${{ secrets.CONFLUENCE_SAM_TOKEN }} \
              --header 'Accept: application/json')

            page_ids=$(echo $PAGES | jq -r -c '.results[].content.id')
            
            echo "PAGE IDS: $page_ids"

            for page_id in $page_ids; do
              echo "PAGE ID: $page_id"
              space_id=$(curl -s -u ${{ secrets.CONFLUENCE_SAM_USER }}:${{ secrets.CONFLUENCE_SAM_TOKEN }} --location "https://risepeople.atlassian.net/wiki/rest/api/content/$page_id" | jq -r '.space.id')
              echo "SPACE ID: $space_id"

              HTML_CONTENT='<div style="width: 65%; display: flex; flex-direction: column; margin: 0 auto;">
                <h2>'"$feature"' updated from '"$AUTHOR"'!</h2>
                <p>'"$PR_DESCRIPTION"'</p>
                <br/>
                <span>Link: <a href="'"$PR_URL"'" target="_blank">'"$PR_URL"'</a></span>
              </div>'
              HTML_CONTENT_JSON=$(echo "$HTML_CONTENT" | jq -Rs .)

              CREATE_PAGE=$(curl --request POST --url 'https://risepeople.atlassian.net/wiki/api/v2/pages' \
                --user ${{ secrets.CONFLUENCE_SAM_USER }}:${{ secrets.CONFLUENCE_SAM_TOKEN }} \
                --header 'Content-Type: application/json' \
                --data "{
                  \"spaceId\": \"$space_id\",
                  \"status\": \"current\",
                  \"title\": \"[UPDATE] $feature updated! PR #$PR_NUMBER - $page_id \",
                  \"parentId\": \"$page_id\",
                  \"body\": {
                    \"representation\": \"storage\",
                    \"value\": $HTML_CONTENT_JSON
                  }
                }"
              )

              echo $CREATE_PAGE
            done
          done
